### ISSUE TITLE
Compile useful voting information links for web content

### ISSUE THREAD

**Issue by sethetter** [devict/voteict#10]
We can store these on the homepage or wherever, but having some links to quality voter information would be great.

The first one can be a link for getting registered -> https://www.vote.org/register-to-vote/kansas/

Maybe include the Eagle's voter guide? If it's available.

I'm sure the League of Women Voters has some great resources too!

**Comment by jakesuellentrop** [comment]
I'll incorporate some of this into the homepage as I'm working on it

**Comment by doshitan** [comment]
https://www.vote411.org/ provides a ton of info, including [voting guides](https://www.vote411.org/ballot) with candidate positions and stuff all in one place. They also have a registration form, but https://ksvotes.org/ might be an easier site for that.

Could also provide a link to the [official state online registration portal](https://www.kdor.ks.gov/Apps/VoterReg/Default.aspx) and [voter info](https://myvoteinfo.voteks.org/VoterView/Home.do) just in case? VOTE411.org does provide links to the official sites so if that's where we send people, that could be good enough.

**Comment by doshitan** [comment]
Oh, and here's the [Eagle's voting guide](http://c3.thevoterguide.org/v/wichita18/m/build.do#).

**Comment by cjprieb** [comment]
I'm going to attempt this issue for hacktoberfest. I haven't used Laravel before, so the first step will be getting a working local version of the site.

**Comment by sethetter** [comment]
@cjprieb feel free to ping me on Slack if you have any issues getting up and running!

**Comment by itsmebennyb** [comment]
Here's a design for the Resources page: https://www.figma.com/file/JylHAXhf1n9urWfOs9WgZ6/VoteICT.org?node-id=179%3A0
