### ISSUE TITLE
Send scheduled messages to a Twitter account, if configured

### ISSUE THREAD

**Issue by sethetter** [devict/voteict#26]
We have the @voteict twitter account, let's use it!

**Comment by imacrayon** [comment]
A quick search looks like https://github.com/thujohn/twitter is a popular Laravel wrapper for the Twitter API

**Comment by sethetter** [comment]
I'm doing this one next!

**Comment by sethetter** [comment]
One thing I'm curious about is possible configuring a twitter account for each locale?

**Comment by imacrayon** [comment]
Here's an example of using multiple accounts set in `/config/services` https://github.com/spatie/scheduled-tweets-app/blob/1bb52d3a02c9cd07f1d4c0ae86d88705038daa59/app/Services/Twitter/RealTwitter.php This might be a good class to steal
