### ISSUE TITLE
Home page design and content

### ISSUE THREAD

**Issue by sethetter** [devict/voteict#4]
Something that explains the service and looks decent for now would be awesome. This could include pulling in whatever base layout / color scheme / other design stuff we want to use going forward.

As for content, we could also include some useful links to things like voter registration and any other voting information resources.

Any designers want to make this look nice? Maybe even a Vote ICT logo?! 😀

**Comment by sethetter** [comment]
I think @kentonh is going to do this.

**Comment by jakesuellentrop** [comment]
I'll work on this!

**Comment by imacrayon** [comment]
@seth is @kenton for sure doing this? If so @jake would you want to tag team issue #6 with me over slack?

**Comment by kentonh** [comment]
@imacrayon I’m going to write some copy at some point soon. Feel free to run with this now, however

**Comment by jakesuellentrop** [comment]
@imacrayon Sounds good to me

**Comment by sethetter** [comment]
Made some progress on this in 6721af8. It's currently deployed at voteict.org. Very basic stuff, but something at least :)
