### ISSUE TITLE
Front-end enhancements with TailwindCSS

### ISSUE THREAD

**Issue by itsmebennyb** [devict/voteict#53]
Looking to jump in and help with some front-end if needed!

Specifically, I would love to start by making the landing page more information-rich, helpful to new/interested users, and simply more interesting to look at.

I have an interest in learning [TailwindCSS](https://tailwindcss.com/) and this would be a great reason to dive in. (@imacrayon mentioned that the site is currently using Bootstrap, but that there could be others in favor of the switch.)

**Comment by imacrayon** [comment]
I'm up for this if it means everything gets a cool new coat of paint. Some more input from others would be helpful in deciding if switching frameworks is a good idea though.

**Comment by itsmebennyb** [comment]
**Boosting the signal on this issue!** 📡 

I'm hoping to help make some homepage improvements in time for this Fall's mayoral election, but that's approaching quickly.

Is there anyone else we can bring to the conversation to reach a yes/no on this? @sethetter @imacrayon

**Comment by imacrayon** [comment]
I think @jakesuellentrop did some front-end work on here at one point

**Comment by sethetter** [comment]
I approve of this! I'm largely _not_ great at anything CSS related, so if you all are willing to take ownership of this transition, it's all good with me!
