### ISSUE TITLE
Show numbers in addition to "ICT-VOTE"

### ISSUE THREAD

**Issue by ccwoolfolk** [devict/voteict#54]
<img width="750" alt="Screenshot 2019-08-19 18 40 10" src="https://user-images.githubusercontent.com/20022270/63306586-cc5a1880-c2b0-11e9-832f-97afd632ceb6.png">

There isn't an easy way to map from phone number letters to numbers in my phone's text message input. I suspect others' phones have the same issue. It may be worth adding the numerical equivalent after or below "ICT-VOTE".

Browser compatibility is likely too problematic for this approach, but an alternative solution would be to use something like `<a href="sms:123-456-7890">ICT-VOTE</a>` (instead of `tel:`). Anyone looking into this should research which mobiles OSs, browsers, etc. support this approach. My cursory search suggests it isn't well enough supported to be used (but I could be wrong).

**Comment by blunket** [comment]
This repo seems worth sharing: https://github.com/smeeckaert/sms-link - I don't know if this repo is still maintained but we might learn something from it.

That's a great idea, I think.

**Comment by JustinDDavis** [comment]
If this issue is still up for grabs, I'd be interested in trying to take it on.

**Comment by imacrayon** [comment]
@justinDDavis I’d say go for it

**Comment by ccwoolfolk** [comment]
@JustinDDavis Just tried this out -- works great for me! Thanks!

@sethetter Closing this out due to #59.
