### ISSUE TITLE
Choose whether messages go to Twitter, SMS, or both

### ISSUE THREAD

**Issue by sethetter** [devict/voteict#62]
Define "targets" for a message, which right now are just Twitter or SMS. Have check boxes on the schedule message form (edit and create). Default to both on. Validate that at least one is checked.

**Comment by JustinDDavis** [comment]
I'd interested in picking this up.

**Comment by sethetter** [comment]
@JustinDDavis it's all yours! Greatly appreciated.

**Comment by JustinDDavis** [comment]
@sethetter, what are your thoughts on the design for storing the target selection in the database? Should there only be a single "target" in the database and we filter out what is sent in the command? Or should there be "target_sms" and "target_twitter" entries to track where messages are needing to go?

**Comment by sethetter** [comment]
@JustinDDavis I think the latter makes the most sense, that way messages can go to both of wanted. Default both to true probably?

**Comment by sethetter** [comment]
Closed by #65!
