### ISSUE TITLE
Archive Page: Pagination Broken

### ISSUE THREAD

**Issue by blunket** [devict/voteict#71]
Seems like by default, Laravel's pagination is set up to work magically with Bootstrap:

https://laravel.com/docs/5.8/pagination
>By default, the views rendered to display the pagination links are compatible with the Bootstrap CSS framework. However, if you are not using Bootstrap, you are free to define your own views to render these links.

But we're not using Bootstrap anymore with #57 so the pagination has broken on the archive page (screenshot):
![image](https://user-images.githubusercontent.com/17580512/67899682-d27e3800-fb30-11e9-8791-7526ee128e42.png)

It looks like there's a very simple pagination method that does nothing but display a "next" and "previous" button, which we could consider as an alternative to numbering out the pages anyway. Or we could build our own pagination view and make it use tailwind classes.

**I'd like to help with this fix**. I should have some time later tonight or at least this week but if it's urgent to fix this then feel free to take care of it without waiting on me.

**Comment by imacrayon** [comment]
Good catch! [This gist](https://gist.github.com/mazedlx/86512703b1dbcb987b2815c31e5173a3) might be useful as a guide for building out the pagination view template, I'll leave the rest up to you.

**Comment by blunket** [comment]
I'm sorry, I don't actually think I have the time to figure out the dev setup currently.

**Comment by imacrayon** [comment]
Fixed in 79d80bb6c41c90539ef50e3748c877a9026b2ff0
